version: '3.5'
networks:
  online-survey-dev:
    driver: bridje
services:
 app:
  container_name: online_survey
  build:
   context:
   dockerfile: DockerFile
   ports:
    - "80:80"
   networks: 
    -online-survey-dev
 db_survey:
    container_name: db_survey
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=survey
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    