FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# COPY *.csproj ./
# RUN dotnet restore

# COPY . ./
# RUN dotnet publish -c Release -o out

# FROM mcr.microsoft.com/dotnet/sdk:8.0 AS final-env
# WORKDIR /app
# COPY --from=build-env /app/out .
# ENTRYPOINT [ "dotnet", "OnlineSurvey.Aplication.dll" ]

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["OnlineSurvey.Aplication/OnlineSurvey.Aplication.csproj","OnlineSurvey.Aplication/"]
RUN dotnet restore "OnlineSurvey.Aplication.csproj"
COPY . .
WORKDIR "/src/OnlineSurvey.Aplication"
RUN dotnet build "OnlineSurvey.Aplication.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet build "OnlineSurvey.Aplication.csproj" -c Release -o /app/publish

FROM base AS final 
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "OnlineSurvey.Aplication.dll" ]