version: '3.5'
networks:
  online-survey-dev:
    driver: bridge
services:
 app:
  container_name: online_survey
  build:
   context:
   dockerfile: DockerFile
   ports:
    - "80:80"
   networks: 
    - online-survey-dev
  depends_on:
   - db_survey
 db_survey:
    container_name: db_survey
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=survey
      - POSTGRES_USER=admin
      - POSTGRES_DB=online_survey
    networks: 
      - online-survey-dev
    volumes:
     - postgres-data: /var/lib/postgresql/data
    image: postgres:14.3-alpine
 volumes:
   postgres-data:


    