version: '3.5'

services:
  db_survey:
    container_name: db_survey
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=survey
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    